config/routes.rb
Rails.application.routes.draw do
  resources :case_requests,
    only: [:new, :create, :show],
    path_names: { new: '' } do
      collection do
        post :help_with_fees
      end
    end

  resources :payments, only: [:show, :update]
  resources :help_with_fees, only: [:show, :update]
  resources :pay_by_account, only: [:show, :update]

  resources :fees, only: [] do
    member do
      get :pay
      get :post_pay
    end
  end

  resources :status, only: [:index]
end

app/controllers/pay_by_account_controller.rb
class PayByAccountController < ApplicationController
  rescue_from GlimrApiClient::PayByAccount::AccountNotFound,
    GlimrApiClient::PayByAccount::InvalidAccountAndConfirmation,
    with: :account_not_found
  include SimplifiedLogging

  def show
    @fee = Fee.find(params[:id])
  end

  def update
    @fee = Fee.find(params[:id])
    ProcessPayByAccount.call(@fee.id, pay_by_account_params)
    redirect_to payment_url(@fee)
  end

  def account_not_found(exception)
    log_error(self.class.name, 'N/A', exception)
    flash[:alert] = t('.account_not_found')
    @fee = Fee.find(params[:id])
    render 'show'
  end

  private

  def pay_by_account_params
    p = params.require(
      [:pay_by_account_reference, :pay_by_account_confirmation]
    )
    { reference: p.first, confirmation: p.last }
  end
end

app/views/pay_by_account/show.html.erb
<% content_for(:left_column) do %>
  <h1 class="heading-large">
    <span class="heading-secondary" data-key="tc_number"><%= @fee.case_reference %></span>
    <%= @fee.case_title %>
  </h1>

  <h2 class="heading-medium"><%= t('.pay') %></h2>

  <p><%= t('.account') %></p>

  <%= form_tag(pay_by_account_url(@fee), method: :put, class: 'js_route') do %>
    <div class="form-group">
      <%= label_tag(:pay_by_account_reference, t('.reference'), class: 'form-label') %>
      <%= text_field_tag(:pay_by_account_reference, nil, class: 'form-control') %>
      <%= label_tag(:pay_by_account_confirmation, t('.confirmation'), class: 'form-label') %>
      <%= text_field_tag(:pay_by_account_confirmation, nil, class: 'form-control') %>
    </div>

    <p>
    <input class="button" type="submit" value="Continue">
  <% end %>
    </p>
<% end %>

<% content_for(:right_column) do %>
  <aside class="payment-summary">
    <div class="inner js-stick-at-top-when-scrolling" style="width: 250px;">
      <h2>Payment summary</h2>
      <p>
      <span id="payment-description"><span data-key="tc_number"><%= @fee.case_reference %></span> - <%= @fee.description %></span>
      </p>
      <p>
      <%= t('.total') %>
      <span id="amount" class="amount"><%= number_to_currency(@fee.amount/100, precision: 0) %></span>
      </p>
    </div>
  </aside>
<% end %>