config/routes.rb
Rails.application.routes.draw do
  resources :case_requests,
    only: [:new, :create, :show],
    path_names: { new: '' } do
      collection do
        post :help_with_fees
      end
    end

  resources :payments, only: [:show, :update]
  resources :help_with_fees, only: [:show, :update]
  resources :pay_by_account, only: [:show, :update]

  resources :fees, only: [] do
    member do
      get :pay
      get :post_pay
    end
  end

  resources :status, only: [:index]
end

app/models/case_request.rb
class CaseRequest < ApplicationRecord
  has_many :case_fees, foreign_key: :case_request_id, class_name: Fee

  validates :case_reference, presence: true
  validates :confirmation_code, presence: true
  before_save :upcase_case_reference

  def process!
    fees.each do |fee|
      prepare_case_fee(fee)
    end
  end

  def all_fees_paid?
    case_fees.all?(&:paid?)
  end

  def fees?
    case_fees.present?
  end

  private

  def upcase_case_reference
    case_reference.upcase!
  end

  def prepare_case_fee(fee)
    case_fees << Fee.new(
      case_reference: case_reference,
      case_title: title,
      description: fee.description,
      amount: fee.amount,
      glimr_id: fee.glimr_id,
      confirmation_code: confirmation_code
    )
  end

  def glimr_case_request
    # This should raise a GlimrApiClient::Case::InvalidCaseNumber
    # exception if the case is not found. But, in the staging (but
    # not dev) environment, that exception is being swallowed, and
    # we end up with a 'case' like this;
    #
    #  <GlimrApiClient::Case:0x007f94ecfc5750
    #    @body=
    #     "{\"message\":\"Invalid CaseNumber/CaseConfirmationCode
    #     combination xxx / YYY\",\"glimrerrorcode\":213}",
    #    @case_reference="xxx",
    #    @confirmation_code="yyy">
    #
    # It's only when we try and call a method on this object that we
    # get a KeyError. So, in the staging environment, the user sees
    # a low-level application error when they search for a case with
    # incorrect reference/confirmation_code
    #
    # The call to fees and the rescue below are a nasty hack to
    # workaround this issue.  TODO: fix this properly, possibly by
    # adding a 'has_errors?' method to the Case class, or by finding
    # and fixing the underlying issue which is preventing the exception
    # from bubbling up properly.

    @glimr_case_request ||= GlimrApiClient::Case.find(
      case_reference,
      confirmation_code
    )

    # If we're looking at a failed find, this will raise a KeyError
    @glimr_case_request.fees

    @glimr_case_request
  rescue KeyError
    raise GlimrApiClient::Case::InvalidCaseNumber
  end

  delegate :fees, :title, to: :glimr_case_request
end

app/controllers/case_requests_controller.rb
class CaseRequestsController < ApplicationController
  rescue_from GlimrApiClient::Case::InvalidCaseNumber, with: :case_not_found
  include SimplifiedLogging

  protect_from_forgery unless: -> { request.format.json? }

  def new
    @case_request = CaseRequest.new
  end

  def create
    @case_request = CaseRequest.new(case_request_params)

    respond_to do |format|
      format.html do
        process_html(@case_request)
      end
      format.json do
        process_json(@case_request)
      end
    end
  end

  def show
    @case_request = CaseRequest.find_by(id: params[:id])
    unless @case_request
      log_error(self.class.name,
        'N/A',
        'case_not_found',
        case_request_id: params[:id])
      flash[:alert] = t('.case_not_found')
      redirect_to new_case_request_url
    end
  end

  private

  def case_not_found(exception)
    log_error(self.class.name, 'N/A', exception, case_request_id: params[:id])
    respond_to do |format|
      format.html do
        flash[:notice] = t('case_requests.could_not_find_case_html')
        redirect_to case_requests_url
      end
      format.json do
        render json: { error: t('.case_not_found') }
      end
    end
  end

  def process_html(case_request)
    if case_request.save
      case_request.process!
      render 'show'
    else
      render 'new'
    end
  end

  def process_json(case_request)
    if case_request.save
      case_request.process!

      render json: { return_url: redirect_url }
    else
      render json: { error: case_request.errors }
    end
  end

  def redirect_url
    if ENV['EXTERNAL_URL']
      ENV['EXTERNAL_URL'] + case_request_path(@case_request.id)
    else
      case_request_url(@case_request.id)
    end
  end

  def case_request_params
    params.require(:case_request).permit(:case_reference, :confirmation_code)
  end
end

app/views/case_requests/new.html.erb
<h1 class="heading-large"><%= t('.find_your_case') %></h1>

<p class="lede">
  <%= t('.enter_details') %>
</p>

<% if flash[:notice] %>
  <%= raw flash[:notice] %>
<% end %>

<%= form_for @case_request do |f| %>
  <%= f.text_field :case_reference %>
  <%= f.text_field :confirmation_code %>
  <%= f.submit(t('.find_case'), class: 'button') %>
<% end %>

<details class="find-case-help">
<summary><span class="summary"><%= t('.dont_know_details') %></span></summary>
  <div class="panel panel-border-narrow">
    <p>
      <%= t('.where_to_find_details') %>
    </p>
  </div>
</details>

app/views/case_requests/show.html.erb
<h1 class="heading-large">
  <%= @case_request.title %>
</h1>

<% if @case_request.fees? %>
  <p>
    <!-- Step numbering goes here -->
  </p>
  <p class="lede">
    <%= t('.case_reference_html', case_reference: @case_request.case_reference) %>
  </p>
  <p><%= t('.you_need_to_pay') %></p>

  <div class="notice notice-payment util_mt-large">
    <i class="icon icon-important">
      <span class="visuallyhidden"><%= t('.warning') %></span>
    </i>
    <strong class="bold-small">
      <%= t('.lose_the_right') %>
    </strong>
  </div>

    <% if @case_request.all_fees_paid? %>
      <%= t('.payments_are_up_to_date') %>
      <%= t('.other_fees_may_be_due') %>
    <% else %>
      <div class="liabilities-list">
        <%= render @case_request.case_fees.first %>
      </div>
      <p><%= t('.select_payment_method') %></p>

      <%= form_tag(payment_url(@case_request.case_fees.first.id), method: :put, class: 'js_route') do %>
      <fieldset>
          <label class='block-label selection-button-radio'>
            <%= radio_button_tag(:payment_method, :card) %>
            <strong><%= t('.debit_or_credit_card') %></strong>
          </label>
          <label class='block-label selection-button-radio'>
            <%= radio_button_tag(:payment_method, :help_with_fees) %>
            <strong><%= t('.help_with_fees') %></strong>
            <br />
            <%= t('.when_to_request_help_with_fees') %>
          </label>
          <label class='block-label selection-button-radio'>
            <%= radio_button_tag(:payment_method, :authorised_account) %>
            <strong><%= t('.authorised_account') %></strong>
            <br />
            <%= t('.if_you_have_an_account') %>
          </label>
        </fieldset>
        <p>
          <%= submit_tag(t('.continue'), class: 'button') %>
        </p>
      <% end %>
    <% end %>
<% else %>
  <p class="lede">
    <%= t('.no_outstanding_fees') %>
  </p>

  <p>
    <%= t('.a_number_of_reasons') %>
  </p>

  <ul class="list list-bullet">
    <%= t('.reasons_html') %>
  </ul>

  <p>
  <a
    href="https://www.gov.uk/courts-tribunals/first-tier-tribunal-tax"
    target="_blank"
    rel="external"><%= t('.contact_the_tribunal') %></a>
    <%= t('.if_you_believe') %>
  </p>
<% end %>