config/routes.rb
Rails.application.routes.draw do
  resources :case_requests,
    only: [:new, :create, :show],
    path_names: { new: '' } do
      collection do
        post :help_with_fees
      end
    end

  resources :payments, only: [:show, :update]
  resources :help_with_fees, only: [:show, :update]
  resources :pay_by_account, only: [:show, :update]

  resources :fees, only: [] do
    member do
      get :pay
      get :post_pay
    end
  end

  resources :status, only: [:index]
end

app/controllers/help_with_fees_controller.rb
class HelpWithFeesController < ApplicationController
  def show
    @fee = Fee.find(params[:id])
  end

  def update
    @fee = Fee.find(params[:id])
    @fee.update_column(:help_with_fees_reference, help_with_fees_params)
    ProcessHelpWithFees.call(@fee.id)
    redirect_to payment_url(@fee)
  end

  private

  def help_with_fees_params
    params.require(:help_with_fees_reference)
  end
end

app/views/help_with_fees/show.html.erb
<% content_for(:left_column) do %>
  <h1 class="heading-large">
    <span class="heading-secondary" data-key="tc_number"><%= @fee.case_reference %></span>
    <%= @fee.case_title %>
  </h1>

  <h2 class="heading-medium"><%= t('.pay') %></h2>

  <p><%= t('.already_applied') %></p>
  <p><%= t('.apply_html') %></p>

  <%= form_tag(help_with_fees_url(@fee), method: :put, class: 'js_route') do %>
    <div class="form-group">
      <%= label_tag(:help_with_fees_reference, t('.reference_number'), class: 'form-label') %>
      <%= text_field_tag(:help_with_fees_reference, nil, class: 'form-control') %>
    </div>

    <p>
    <input class="button" type="submit" value="Continue">
  <% end %>
    </p>
<% end %>

<% content_for(:right_column) do %>
  <aside class="payment-summary">
    <div class="inner js-stick-at-top-when-scrolling" style="width: 250px;">
      <h2>Payment summary</h2>
      <p>
      <span id="payment-description"><span data-key="tc_number"><%= @fee.case_reference %></span> - <%= @fee.description %></span>
      </p>
      <p>
      <%= t('.total') %>
      <span id="amount" class="amount"><%= number_to_currency(@fee.amount/100, precision: 0) %></span>
      </p>
    </div>
  </aside>
<% end %>