config/routes.rb
Rails.application.routes.draw do
  resources :case_requests,
    only: [:new, :create, :show],
    path_names: { new: '' } do
      collection do
        post :help_with_fees
      end
    end

  resources :payments, only: [:show, :update]
  resources :help_with_fees, only: [:show, :update]
  resources :pay_by_account, only: [:show, :update]

  resources :fees, only: [] do
    member do
      get :pay
      get :post_pay
    end
  end

  resources :status, only: [:index]
end

app/models/fee.rb
require 'bcrypt'

class Fee < ApplicationRecord
  include BCrypt

  attr_accessor :confirmation_code

  validates :case_reference,
    :glimr_id,
    :description,
    :amount,
    presence: true

  belongs_to :case_request

  before_save :crypt_confirmation_code, if: :confirmation_code
  after_create :set_govpay_reference!

  def govpay_description
    "#{case_reference} - #{description}"
  end

  def amount_in_pounds
    amount / 100.0
  end

  def status_known?
    govpay_payment_status.present?
  end

  def paid?
    govpay_payment_status.eql?('success')
  end

  def failed?
    status_known? && !paid?
  end

  private

  def crypt_confirmation_code
    self.confirmation_code_digest = Password.create(confirmation_code)
  end

  def set_govpay_reference!
    update(govpay_reference: "#{glimr_id}G#{timestamp}")
  end

  def timestamp
    Time.zone.now.strftime('%Y%m%d%H%M%S')
  end
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  def pay
    operation = CreatePayment.call(params[:id])
    redirect_to operation.next_url
  rescue GovukPayApiClient::Unavailable
    redirect_to root_path, alert: t('apis.service_unavailable')
  end

  def post_pay
    operation = ProcessPayment.call(params[:id])

    @fee = operation.fee
    if operation.error?
      flash[:error] = operation.error_message || t('.payment_error')
      # rubocop:disable Style/AndOr
      # Know rubocop issue.
      render 'post_pay_error' and return
      # rubocop:enable Style/AndOr
    end
    redirect_to payment_url(@fee)
  rescue GovukPayApiClient::Unavailable
    redirect_to root_path, alert: t('apis.payment_status_unavailable')
  end
end

app/views/fees/_fee.html.erb
<h2 class="heading-large">
  <%= t('.header_html', amount: number_to_currency(fee.amount_in_pounds, precision: 0)) %>
</h2>

app/views/fees/post_pay_error.html.erb
<h1 class="heading-large">
  <span class="heading-secondary"><%= @fee.case_reference %></span>
  <%= @fee.case_title %>
</h1>

<div class="error-summary">
  <h2 class="heading-medium heading-error"><%= t('.payment_not_taken') %></h2>
  <p>
    <%= flash[:error] %>.
  </p>
  <p class="font-xsmall">
    <%= t('.try_again_copy') %>
  </p>
  <p>
    <%= link_to t('.try_again'), pay_fee_path(@fee), class: 'button' %>
  </p>
</div>

<p>
  <%= t('.made_in_error') %>
</p>

<div class="notice notice-payment">
 <i class="icon icon-important">
   <span class="visuallyhidden"><%= t('.warning') %></span>
 </i>
 <strong class="bold-small">
   <%= t('.lose_the_right_to_appeal') %>
 </strong>
</div>

<p>
  <%= link_to t('fees.find_another_case'), new_case_request_path, class: 'link-back' %>
</p>

app/views/fees/post_pay_success.html.erb
<h1 class="heading-large">
  <span class="heading-secondary"><%= @fee.case_reference %></span>
  <%= @fee.case_title %>
</h1>

<div class="govuk-box-highlight">
  <h1 class="bold-large"><%= t('.payment_successful') %></h1>
<p>
<%= t('.your_payment_reference') %></ br>
<strong class="heading-medium"><%= @fee.govpay_payment_id.upcase %></strong>
</p>
</div>
<p><%= t('.confirmation_email') %></p>

<h2 class="heading-medium"><%= t('.what_happens_next') %></h2>
<p>
  <%= t('.what_the_tribunal_will_do') %>
</p>
<p>
  <%= t('.what_did_you_think_html') %>
</p>

<p>
  <%= link_to t('fees.find_another_case'), new_case_request_path, class: 'link-back' %>
</p>